export type ReportDef = {
  label: string;
  value: string;
  group: string;
  description: string;
  columns: { key: string; label: string }[];
  hasDateRange: boolean;
};

export const REPORT_TYPES: ReportDef[] = [
  {
    label: "Delays",
    value: "daily-delays",
    group: "Daily Log",
    description: "All delay entries logged in the daily log, including type, duration and location.",
    hasDateRange: true,
    columns: [
      { key: "log_date", label: "Date" },
      { key: "delay_type", label: "Delay Type" },
      { key: "start_time", label: "Start Time" },
      { key: "end_time", label: "End Time" },
      { key: "duration_hours", label: "Duration (hrs)" },
      { key: "location", label: "Location" },
      { key: "comments", label: "Comments" },
    ],
  },
  {
    label: "Manpower",
    value: "daily-manpower",
    group: "Daily Log",
    description:
      "Workforce / manpower log entries per company. Includes worker counts, hours, cost codes, and the user who created each daily log (created_by).",
    hasDateRange: true,
    columns: [
      { key: "log_date", label: "Date" },
      { key: "company", label: "Company" },
      { key: "workers", label: "Workers" },
      { key: "hours", label: "Hours" },
      { key: "location", label: "Location" },
      { key: "cost_code", label: "Cost Code" },
      { key: "comments", label: "Comments" },
      { key: "created_by", label: "Created By" },
    ],
  },
  {
    label: "Weather Observations",
    value: "daily-weather",
    group: "Daily Log",
    description: "Weather conditions recorded each day, including sky, temperature, wind and precipitation.",
    hasDateRange: true,
    columns: [
      { key: "log_date", label: "Date" },
      { key: "time_observed", label: "Time" },
      { key: "sky", label: "Sky" },
      { key: "temperature", label: "Temp" },
      { key: "wind", label: "Wind" },
      { key: "avg_precipitation", label: "Precipitation" },
      { key: "ground_sea", label: "Ground/Sea" },
      { key: "delay", label: "Delay?" },
      { key: "calamity", label: "Calamity" },
      { key: "comments", label: "Comments" },
    ],
  },
  {
    label: "Safety Violations",
    value: "daily-safety",
    group: "Daily Log",
    description: "Safety notices issued on site, including subject, recipient and compliance due date.",
    hasDateRange: true,
    columns: [
      { key: "log_date", label: "Date" },
      { key: "time", label: "Time" },
      { key: "subject", label: "Subject" },
      { key: "safety_notice", label: "Safety Notice" },
      { key: "issued_to", label: "Issued To" },
      { key: "compliance_due", label: "Compliance Due" },
      { key: "comments", label: "Comments" },
    ],
  },
  {
    label: "Accidents",
    value: "daily-accidents",
    group: "Daily Log",
    description: "Accident and incident records logged in the daily log.",
    hasDateRange: true,
    columns: [
      { key: "log_date", label: "Date" },
      { key: "time", label: "Time" },
      { key: "party_involved", label: "Party Involved" },
      { key: "company_involved", label: "Company" },
      { key: "comments", label: "Comments" },
    ],
  },
  {
    label: "Inspections",
    value: "daily-inspections",
    group: "Daily Log",
    description: "Site inspection records including type, inspector, and location details.",
    hasDateRange: true,
    columns: [
      { key: "log_date", label: "Date" },
      { key: "inspection_type", label: "Type" },
      { key: "inspecting_entity", label: "Entity" },
      { key: "inspector_name", label: "Inspector" },
      { key: "start_time", label: "Start" },
      { key: "end_time", label: "End" },
      { key: "location", label: "Location" },
      { key: "inspection_area", label: "Area" },
      { key: "comments", label: "Comments" },
    ],
  },
  {
    label: "Deliveries",
    value: "daily-deliveries",
    group: "Daily Log",
    description: "Material and equipment deliveries tracked in the daily log.",
    hasDateRange: true,
    columns: [
      { key: "log_date", label: "Date" },
      { key: "time", label: "Time" },
      { key: "delivery_from", label: "Delivery From" },
      { key: "tracking_number", label: "Tracking #" },
      { key: "contents", label: "Contents" },
      { key: "comments", label: "Comments" },
    ],
  },
  {
    label: "Visitors",
    value: "daily-visitors",
    group: "Daily Log",
    description: "Visitor log entries including arrival/departure times.",
    hasDateRange: true,
    columns: [
      { key: "log_date", label: "Date" },
      { key: "visitor", label: "Visitor" },
      { key: "start_time", label: "Start" },
      { key: "end_time", label: "End" },
      { key: "comments", label: "Comments" },
    ],
  },
  {
    label: "Notes & Issues",
    value: "daily-notes",
    group: "Daily Log",
    description: "General notes and flagged issues recorded during daily log entries.",
    hasDateRange: true,
    columns: [
      { key: "log_date", label: "Date" },
      { key: "is_issue", label: "Issue?" },
      { key: "location", label: "Location" },
      { key: "comments", label: "Comments" },
    ],
  },
  {
    label: "Commitments Summary",
    value: "commitments-summary",
    group: "Financial Management",
    description:
      "All purchase orders and subcontracts with status, contract amounts, approved change orders, and remaining balances.",
    hasDateRange: false,
    columns: [
      { key: "number", label: "#" },
      { key: "type", label: "Type" },
      { key: "contract_company", label: "Company" },
      { key: "title", label: "Title" },
      { key: "status", label: "Status" },
      { key: "sov_accounting_method", label: "Accounting Method" },
      { key: "original_contract_amount", label: "Original Amount" },
      { key: "approved_change_orders", label: "Approved COs" },
      { key: "pending_change_orders", label: "Pending COs" },
      { key: "erp_status", label: "ERP Status" },
    ],
  },
  {
    label: "Change Events",
    value: "change-events",
    group: "Financial Management",
    description: "Change events log with scope classification, ROM amounts, and linkage to change orders.",
    hasDateRange: false,
    columns: [
      { key: "number", label: "#" },
      { key: "title", label: "Title" },
      { key: "status", label: "Status" },
      { key: "scope", label: "Scope" },
      { key: "rom_amount", label: "ROM Amount" },
      { key: "created_at", label: "Created" },
    ],
  },
  {
    label: "Commitment Change Orders",
    value: "commitment-change-orders",
    group: "Financial Management",
    description: "All commitment change orders across the project, including status, amount, and linked contracts.",
    hasDateRange: false,
    columns: [
      { key: "number", label: "#" },
      { key: "title", label: "Title" },
      { key: "status", label: "Status" },
      { key: "contract_company", label: "Company" },
      { key: "contract_name", label: "Contract" },
      { key: "amount", label: "Amount" },
      { key: "change_reason", label: "Change Reason" },
      { key: "due_date", label: "Due Date" },
    ],
  },
  {
    label: "Budget Summary",
    value: "budget-summary",
    group: "Financial Management",
    description: "Budget line items showing original budget, committed costs, and variance by cost code.",
    hasDateRange: false,
    columns: [
      { key: "cost_code", label: "Cost Code" },
      { key: "description", label: "Description" },
      { key: "original_budget", label: "Original Budget" },
      { key: "committed_costs", label: "Committed Costs" },
      { key: "variance", label: "Variance" },
    ],
  },
  {
    label: "RFIs",
    value: "rfis",
    group: "Project Tools",
    description: "All Requests for Information on the project, with status and due dates.",
    hasDateRange: false,
    columns: [
      { key: "rfi_number", label: "RFI #" },
      { key: "subject", label: "Subject" },
      { key: "status", label: "Status" },
      { key: "due_date", label: "Due Date" },
      { key: "created_at", label: "Created" },
    ],
  },
  {
    label: "Submittals",
    value: "submittals",
    group: "Project Tools",
    description: "Submittal log including type, status, submission and issue dates.",
    hasDateRange: false,
    columns: [
      { key: "submittal_number", label: "Submittal #" },
      { key: "title", label: "Title" },
      { key: "status", label: "Status" },
      { key: "submittal_type", label: "Type" },
      { key: "submit_by", label: "Submit By" },
      { key: "received_date", label: "Received" },
      { key: "issue_date", label: "Issued" },
      { key: "cost_code", label: "Cost Code" },
    ],
  },
  {
    label: "Tasks",
    value: "tasks",
    group: "Project Tools",
    description: "Open and closed tasks assigned to the project team.",
    hasDateRange: false,
    columns: [
      { key: "task_number", label: "Task #" },
      { key: "title", label: "Title" },
      { key: "status", label: "Status" },
      { key: "category", label: "Category" },
      { key: "created_at", label: "Created" },
    ],
  },
  {
    label: "Punch List",
    value: "punch-list",
    group: "Project Tools",
    description: "Punch list items with type, trade, priority and location details.",
    hasDateRange: false,
    columns: [
      { key: "item_number", label: "Item #" },
      { key: "title", label: "Title" },
      { key: "status", label: "Status" },
      { key: "type", label: "Type" },
      { key: "trade", label: "Trade" },
      { key: "priority", label: "Priority" },
      { key: "due_date", label: "Due Date" },
      { key: "location", label: "Location" },
    ],
  },
];
