// AUTO-GENERATED catalogs for source-less 360 report entities.
// Each entity's rows live in the generic report_records table; every field is
// stored in report_fields JSONB and rendered in the violet Report Fields UI.
import type { ReportFieldDef } from "@/components/ReportFieldsSection";

export type ReportRecordEntity = { slug: string; label: string; fields: ReportFieldDef[] };

export const REPORT_RECORD_ENTITIES: ReportRecordEntity[] = [
  {
    slug: "owner-invoices",
    label: "Owner Invoice",
    fields: [
      { key: "number", label: "#" },
      { key: "status", label: "Status" },
      { key: "billing_period", label: "Billing Period" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "architect", label: "Architect" },
      { key: "assigned_to_current_workflow_step", label: "Assigned to Current Workflow Step" },
      { key: "attachments_count", label: "Attachments Count" },
      { key: "balance_to_finish_including_retainage", label: "Balance To Finish (Including Retainage)", type: "currency" },
      { key: "billing_date", label: "Billing Date", type: "date" },
      { key: "billing_period_end_date", label: "Billing Period End Date", type: "date" },
      { key: "billing_period_start_date", label: "Billing Period Start Date", type: "date" },
      { key: "contract_sum_to_date", label: "Contract Sum To Date", type: "currency" },
      { key: "currency_code", label: "Currency Code" },
      { key: "current_payment_due", label: "Current Payment Due", type: "currency" },
      { key: "current_workflow_response", label: "Current Workflow Response" },
      { key: "current_workflow_step", label: "Current Workflow Step" },
      { key: "current_workflow_step_due_date", label: "Current Workflow Step Due Date", type: "date" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "erp_latest_status", label: "ERP Latest Status" },
      { key: "erp_updated_at", label: "ERP Updated At", type: "date" },
      { key: "erp_user_name", label: "ERP User Name" },
      { key: "gross_amount", label: "Gross Amount", type: "currency" },
      { key: "gross_amount_plus_tax", label: "Gross Amount plus Tax", type: "currency" },
      { key: "is_last", label: "Is Last" },
      { key: "less_previous_certificates_for_payment", label: "Less Previous Certificates For Payment", type: "currency" },
      { key: "materials_presently_stored", label: "Materials Presently Stored", type: "currency" },
      { key: "net_amount", label: "Net Amount", type: "currency" },
      { key: "net_amount_plus_tax", label: "Net Amount plus Tax", type: "currency" },
      { key: "net_changes_by_change_order", label: "Net Changes By Change Order", type: "currency" },
      { key: "paid_amount", label: "Paid Amount", type: "currency" },
      { key: "percent_complete", label: "Percent Complete" },
      { key: "period_end", label: "Period End", type: "date" },
      { key: "period_start", label: "Period Start", type: "date" },
      { key: "position", label: "Position" },
      { key: "retainage_of_completed_work_percent", label: "Retainage Of Completed Work (%)" },
      { key: "retainage_of_completed_work_dollar", label: "Retainage of Completed Work ($)", type: "currency" },
      { key: "retainage_of_stored_material_percent", label: "Retainage Of Stored Material (%)" },
      { key: "retainage_of_stored_material_dollar", label: "Retainage Of Stored Material ($)", type: "currency" },
      { key: "synced_with_accounting", label: "Synced With Accounting" },
      { key: "tax_applicable_to_this_payment", label: "Tax applicable to this payment", type: "currency" },
      { key: "tax_total", label: "Tax Total", type: "currency" },
      { key: "taxable_amount", label: "Taxable Amount", type: "currency" },
      { key: "total_changes_approved_additions", label: "Total Changes Approved - Additions", type: "currency" },
      { key: "total_changes_approved_deductions", label: "Total Changes Approved - Deductions", type: "currency" },
      { key: "total_changes_approved_in_previous_months_by_owner_client_additions", label: "Total Changes Approved In Previous Months By Owner/Client - Additions", type: "currency" },
      { key: "total_changes_approved_in_previous_months_by_owner_client_deductions", label: "Total Changes Approved In Previous Months By Owner/Client - Deductions", type: "currency" },
      { key: "total_changes_approved_this_month_additions", label: "Total Changes Approved This Month - Additions", type: "currency" },
      { key: "total_changes_approved_this_month_deductions", label: "Total Changes Approved This Month - Deductions", type: "currency" },
      { key: "total_completed_and_stored_to_date", label: "Total Completed And Stored To Date", type: "currency" },
      { key: "total_earned_less_retainage", label: "Total Earned Less Retainage", type: "currency" },
      { key: "total_retainage", label: "Total Retainage", type: "currency" },
      { key: "workflow_assignment_duration_days", label: "Workflow Assignment Duration (Days)" },
    ],
  },
  {
    slug: "owner-invoice-line-items",
    label: "Owner Invoice Line Item",
    fields: [
      { key: "budget_code", label: "Budget Code" },
      { key: "description", label: "Description" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "balance_to_finish", label: "Balance To Finish", type: "currency" },
      { key: "currency_code", label: "Currency Code" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "description_of_work", label: "Description Of Work" },
      { key: "gross_amount", label: "Gross Amount", type: "currency" },
      { key: "gross_amount_plus_tax", label: "Gross Amount plus Tax", type: "currency" },
      { key: "item_number", label: "Item Number" },
      { key: "line_item_type", label: "Line Item Type" },
      { key: "materials_presently_stored", label: "Materials Presently Stored", type: "currency" },
      { key: "materials_presently_stored_quantity", label: "Materials Presently Stored Quantity" },
      { key: "materials_retainage_this_period_percent", label: "Materials Retainage This Period (%)" },
      { key: "materials_retainage_this_period_dollar", label: "Materials Retainage This Period ($)", type: "currency" },
      { key: "materials_retainage_to_date_percent", label: "Materials Retainage To Date (%)" },
      { key: "materials_retainage_to_date_dollar", label: "Materials Retainage To Date ($)", type: "currency" },
      { key: "materials_stored_from_previous", label: "Materials Stored From Previous", type: "currency" },
      { key: "net_amount", label: "Net Amount", type: "currency" },
      { key: "net_amount_plus_tax", label: "Net Amount plus Tax", type: "currency" },
      { key: "new_materials", label: "New Materials", type: "currency" },
      { key: "new_materials_retainage", label: "New Materials Retainage", type: "currency" },
      { key: "new_materials_stored_quantity", label: "New Materials Stored Quantity" },
      { key: "previous_materials_retainage", label: "Previous Materials Retainage" },
      { key: "previous_materials_retainage_dollar", label: "Previous Materials Retainage ($)", type: "currency" },
      { key: "previous_materials_stored", label: "Previous Materials Stored", type: "currency" },
      { key: "previous_materials_stored_quantity", label: "Previous Materials Stored Quantity" },
      { key: "previous_total_retainage_dollar", label: "Previous Total Retainage ($)", type: "currency" },
      { key: "previous_work_retainage_dollar", label: "Previous Work Retainage ($)", type: "currency" },
      { key: "quantity", label: "Quantity" },
      { key: "scheduled_value", label: "Scheduled Value", type: "currency" },
      { key: "scheduled_value_quantity", label: "Scheduled Value Quantity" },
      { key: "tax_amount", label: "Tax Amount", type: "currency" },
      { key: "tax_codes", label: "Tax Codes" },
      { key: "total_completed_and_stored_materials_to_date_percent", label: "Total Completed And Stored Materials To Date (%)" },
      { key: "total_completed_and_stored_materials_to_date_dollar", label: "Total Completed And Stored Materials To Date ($)", type: "currency" },
      { key: "total_completed_and_stored_to_date_quantity", label: "Total Completed and Stored To Date Quantity" },
      { key: "total_completed_stored", label: "Total Completed Stored", type: "currency" },
      { key: "total_retainage_to_date_dollar", label: "Total Retainage To Date ($)", type: "currency" },
      { key: "total_work_retainage_dollar", label: "Total Work Retainage ($)", type: "currency" },
      { key: "unit_of_measure", label: "Unit Of Measure" },
      { key: "unit_price", label: "Unit Price", type: "currency" },
      { key: "work_completed_from_previous_application_percent", label: "Work Completed From Previous Application (%)" },
      { key: "work_completed_from_previous_application_dollar", label: "Work Completed From Previous Application ($)", type: "currency" },
      { key: "work_completed_from_previous_application_quantity", label: "Work Completed From Previous Application Quantity" },
      { key: "work_completed_retainage_percent", label: "Work Completed Retainage Percent" },
      { key: "work_completed_this_period_percent", label: "Work Completed This Period (%)" },
      { key: "work_completed_this_period_dollar", label: "Work Completed This Period ($)", type: "currency" },
      { key: "work_completed_this_period_quantity", label: "Work Completed This Period Quantity" },
      { key: "work_retainage_released_this_period_dollar", label: "Work Retainage Released This Period ($)", type: "currency" },
      { key: "work_retainage_this_period", label: "Work Retainage This Period", type: "currency" },
      { key: "work_retainage_this_period_percent", label: "Work Retainage This Period (%)" },
      { key: "work_retainage_this_period_dollar", label: "Work Retainage This Period ($)", type: "currency" },
    ],
  },
  {
    slug: "subcontractor-invoices",
    label: "Subcontractor Invoice",
    fields: [
      { key: "assigned_to_current_workflow_step", label: "Assigned to Current Workflow Step" },
      { key: "attachments_count", label: "Attachments Count" },
      { key: "balance_to_finish", label: "Balance To Finish", type: "currency" },
      { key: "billing_date", label: "Billing Date", type: "date" },
      { key: "billing_period_end", label: "Billing Period End", type: "date" },
      { key: "billing_period_start", label: "Billing Period Start", type: "date" },
      { key: "billing_type", label: "Billing Type" },
      { key: "contract_sum_to_date", label: "Contract Sum To Date", type: "currency" },
      { key: "created_by", label: "Created By" },
      { key: "currency_code", label: "Currency Code" },
      { key: "current_payment_due", label: "Current Payment Due", type: "currency" },
      { key: "current_workflow_response", label: "Current Workflow Response" },
      { key: "current_workflow_step", label: "Current Workflow Step" },
      { key: "current_workflow_step_due_date", label: "Current Workflow Step Due Date", type: "date" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "early_pay_fee_amount", label: "Early Pay Fee Amount", type: "currency" },
      { key: "early_pay_rate", label: "Early Pay Rate" },
      { key: "early_pay_status", label: "Early Pay Status" },
      { key: "erp_latest_status", label: "ERP Latest Status" },
      { key: "erp_updated_at", label: "ERP Updated At", type: "date" },
      { key: "erp_user_name", label: "ERP User Name" },
      { key: "gross_amount", label: "Gross Amount", type: "currency" },
      { key: "gross_amount_plus_tax", label: "Gross Amount plus Tax", type: "currency" },
      { key: "invoice_end_date", label: "Invoice End Date", type: "date" },
      { key: "invoice_start_date", label: "Invoice Start Date", type: "date" },
      { key: "is_last", label: "Is Last" },
      { key: "less_previous_certificates_for_payment", label: "Less Previous Certificates for Payment", type: "currency" },
      { key: "missed_payment_due_date", label: "Missed Payment Due Date", type: "date" },
      { key: "net_amount", label: "Net Amount", type: "currency" },
      { key: "net_amount_plus_tax", label: "Net Amount plus Tax", type: "currency" },
      { key: "net_changes_by_change_order", label: "Net Changes By Change Order", type: "currency" },
      { key: "number", label: "Number" },
      { key: "original_payment_due", label: "Original Payment Due", type: "currency" },
      { key: "overall_comments", label: "Overall Comments" },
      { key: "paid_amount", label: "Paid Amount", type: "currency" },
      { key: "payment_date", label: "Payment Date", type: "date" },
      { key: "payment_due_date", label: "Payment Due Date", type: "date" },
      { key: "payment_status", label: "Payment Status" },
      { key: "payments_count", label: "Payments Count" },
      { key: "percent_complete", label: "Percent Complete" },
      { key: "position", label: "Position" },
      { key: "retainage_of_completed_work_percent", label: "Retainage Of Completed Work (%)" },
      { key: "retainage_of_completed_work_dollar", label: "Retainage Of Completed Work ($)", type: "currency" },
      { key: "retainage_of_stored_material_percent", label: "Retainage Of Stored Material (%)" },
      { key: "retainage_of_stored_material_dollar", label: "Retainage Of Stored Material ($)", type: "currency" },
      { key: "status", label: "Status" },
      { key: "submitted_date", label: "Submitted Date", type: "date" },
      { key: "synced_with_accounting", label: "Synced With Accounting" },
      { key: "tax_total", label: "Tax Total", type: "currency" },
      { key: "taxable_amount", label: "Taxable Amount", type: "currency" },
      { key: "total_changes_approved_additions", label: "Total Changes Approved Additions", type: "currency" },
      { key: "total_changes_approved_deductions", label: "Total Changes Approved Deductions", type: "currency" },
      { key: "total_changes_approved_in_previous_months_by_owner_client_additions", label: "Total Changes Approved In Previous Months By Owner/Client Additions", type: "currency" },
      { key: "total_changes_approved_in_previous_months_by_owner_client_deductions", label: "Total Changes Approved In Previous Months By Owner/Client Deductions", type: "currency" },
      { key: "total_changes_approved_this_month_additions", label: "Total Changes Approved This Month Additions", type: "currency" },
      { key: "total_changes_approved_this_month_deductions", label: "Total Changes Approved This Month Deductions", type: "currency" },
      { key: "total_completed_and_stored_to_date", label: "Total Completed And Stored To Date", type: "currency" },
      { key: "total_contract_amount", label: "Total Contract Amount", type: "currency" },
      { key: "total_earned_less_retainage", label: "Total Earned Less Retainage", type: "currency" },
      { key: "total_payments_amount", label: "Total Payments Amount", type: "currency" },
      { key: "total_proposed_amount", label: "Total Proposed Amount", type: "currency" },
      { key: "total_retainage", label: "Total Retainage", type: "currency" },
      { key: "total_tax", label: "Total Tax", type: "currency" },
      { key: "workflow_assignment_duration_days", label: "Workflow Assignment Duration (Days)" },
    ],
  },
  {
    slug: "subcontractor-invoice-line-items",
    label: "Subcontractor Invoice Line Item",
    fields: [
      { key: "balance_to_finish", label: "Balance To Finish", type: "currency" },
      { key: "comment_status_reason", label: "Comment (Status Reason)" },
      { key: "currency_code", label: "Currency Code" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "description_of_work", label: "Description of Work" },
      { key: "gross_amount", label: "Gross Amount", type: "currency" },
      { key: "gross_amount_plus_tax", label: "Gross Amount plus Tax", type: "currency" },
      { key: "line_item_type", label: "Line Item Type" },
      { key: "materials_presently_stored", label: "Materials Presently Stored", type: "currency" },
      { key: "materials_presently_stored_quantity", label: "Materials Presently Stored Quantity" },
      { key: "materials_previously_stored_quantity", label: "Materials Previously Stored Quantity" },
      { key: "materials_retainage_from_previous_application", label: "Materials Retainage From Previous Application", type: "currency" },
      { key: "materials_retainage_this_period_dollar", label: "Materials Retainage This Period ($)", type: "currency" },
      { key: "net_amount", label: "Net Amount", type: "currency" },
      { key: "net_amount_plus_tax", label: "Net Amount plus Tax", type: "currency" },
      { key: "new_materials_quantity", label: "New Materials Quantity" },
      { key: "new_materials_retainage", label: "New Materials Retainage", type: "currency" },
      { key: "new_materials_stored", label: "New Materials Stored", type: "currency" },
      { key: "new_quantity", label: "New Quantity" },
      { key: "previous_materials_retainage", label: "Previous Materials Retainage", type: "currency" },
      { key: "previous_materials_stored", label: "Previous Materials Stored", type: "currency" },
      { key: "previous_quantity", label: "Previous Quantity" },
      { key: "proposed_amount", label: "Proposed Amount", type: "currency" },
      { key: "retainage_work_dollar", label: "Retainage Work ($)", type: "currency" },
      { key: "scheduled_value", label: "Scheduled Value", type: "currency" },
      { key: "scheduled_value_quantity", label: "Scheduled Value Quantity" },
      { key: "status", label: "Status" },
      { key: "tax_amount", label: "Tax Amount", type: "currency" },
      { key: "tax_codes", label: "Tax Codes" },
      { key: "total_completed_stored_to_date_percent", label: "Total Completed & Stored to Date (%)" },
      { key: "total_completed_stored_to_date_dollar", label: "Total Completed & Stored to Date ($)", type: "currency" },
      { key: "total_completed_stored_to_date_dollar_from_previous", label: "Total Completed & Stored To Date ($) from Previous", type: "currency" },
      { key: "total_completed_stored_to_date_quantity", label: "Total Completed & Stored to Date Quantity" },
      { key: "total_materials_retainage", label: "Total Materials Retainage", type: "currency" },
      { key: "total_materials_retainage_percent", label: "Total Materials Retainage (%)" },
      { key: "total_retainage", label: "Total Retainage", type: "currency" },
      { key: "total_retainage_from_previous_application", label: "Total Retainage From Previous Application", type: "currency" },
      { key: "total_retainage_held_this_period", label: "Total Retainage Held This Period", type: "currency" },
      { key: "total_retainage_released", label: "Total Retainage Released", type: "currency" },
      { key: "unit_price", label: "Unit Price", type: "currency" },
      { key: "work_completed_from_previous_application", label: "Work Completed From Previous Application", type: "currency" },
      { key: "work_completed_from_previous_application_percent", label: "Work Completed From Previous Application (%)" },
      { key: "work_completed_this_period", label: "Work Completed This Period", type: "currency" },
      { key: "work_completed_this_period_percent", label: "Work Completed this Period (%)" },
      { key: "work_retainage_from_previous_application", label: "Work Retainage From Previous Application", type: "currency" },
      { key: "work_retainage_this_period_percent", label: "Work Retainage This Period (%)" },
      { key: "work_retainage_this_period_dollar", label: "Work Retainage This Period ($)", type: "currency" },
    ],
  },
  {
    slug: "payments-issued",
    label: "Payment Issued",
    fields: [
      { key: "number", label: "#" },
      { key: "vendor", label: "Vendor" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "paid_on", label: "Paid On", type: "date" },
    ],
  },
  {
    slug: "payments-received",
    label: "Payment Received",
    fields: [
      { key: "number", label: "#" },
      { key: "from", label: "From" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "received_on", label: "Received On", type: "date" },
    ],
  },
  {
    slug: "employees",
    label: "Employee",
    fields: [
      { key: "company_employee_id", label: "Company Employee ID" },
      { key: "company_name", label: "Company Name" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "first_name", label: "First Name" },
      { key: "full_name", label: "Full Name" },
      { key: "is_active", label: "Is Active" },
      { key: "job_title", label: "Job Title" },
      { key: "last_name", label: "Last Name" },
      { key: "tags_keywords", label: "Tags/Keywords" },
    ],
  },
  {
    slug: "labor-allocations",
    label: "Labor Allocation",
    fields: [
      { key: "created_by", label: "Created By" },
      { key: "date", label: "Date", type: "date" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "hours", label: "Hours" },
    ],
  },
  {
    slug: "actual-production-quantities",
    label: "Actual Production Quantity",
    fields: [
      { key: "created_by", label: "Created By" },
      { key: "date", label: "Date", type: "date" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "note", label: "Note" },
      { key: "unit_of_measure", label: "Unit Of Measure" },
      { key: "units_installed", label: "Units Installed" },
    ],
  },
  {
    slug: "budgeted-production-quantities",
    label: "Budgeted Production Quantity",
    fields: [
      { key: "created_by", label: "Created By" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "quantity", label: "Quantity" },
      { key: "unit_of_measure", label: "Unit Of Measure" },
    ],
  },
  {
    slug: "budget-change-production-quantities",
    label: "Budget Change Production Quantity",
    fields: [
      { key: "comment", label: "Comment" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "description", label: "Description" },
      { key: "quantity", label: "Quantity" },
      { key: "unit_of_measure", label: "Unit Of Measure" },
    ],
  },
  {
    slug: "change-event-production-quantities",
    label: "Change Event Production Quantity",
    fields: [
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "description", label: "Description" },
      { key: "quantity", label: "Quantity" },
      { key: "unit_of_measure", label: "Unit Of Measure" },
    ],
  },
  {
    slug: "prime-contract-change-order-production-quantities",
    label: "Prime Contract Change Order Production Quantity",
    fields: [
      { key: "approved_changes_to_budgeted_quantities", label: "Approved Changes to Budgeted Quantities" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "description", label: "Description" },
      { key: "quantity", label: "Quantity" },
      { key: "unit_of_measure", label: "Unit Of Measure" },
    ],
  },
  {
    slug: "erp-job-costs",
    label: "ERP Job Costs Summary",
    fields: [
      { key: "cost_code", label: "Cost Code" },
      { key: "job_to_date", label: "Job to Date", type: "currency" },
      { key: "direct_costs", label: "Direct Costs", type: "currency" },
      { key: "synced_at", label: "Synced", type: "date" },
    ],
  },
  {
    slug: "invoice-compliance",
    label: "Invoice Compliance",
    fields: [
      { key: "invoice_number", label: "Invoice #" },
      { key: "compliant", label: "Compliant" },
      { key: "missing_items", label: "Missing Items" },
    ],
  },
  {
    slug: "monitored-resources",
    label: "Monitored Resource",
    fields: [
      { key: "name", label: "Name" },
      { key: "type", label: "Type" },
      { key: "status", label: "Status" },
    ],
  },
  {
    slug: "commitment-change-order-line-items",
    label: "Commitment Change Order Line Item",
    fields: [
      { key: "budget_code", label: "Budget Code" },
      { key: "description", label: "Description" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "amount_including_markup", label: "Amount (Including Markup)", type: "currency" },
      { key: "approved_amount", label: "Approved Amount", type: "currency" },
      { key: "approved_amount_including_markup", label: "Approved Amount (Including Markup)", type: "currency" },
      { key: "currency_code", label: "Currency Code" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "draft_amount", label: "Draft Amount", type: "currency" },
      { key: "draft_amount_including_markup", label: "Draft Amount (Including Markup)", type: "currency" },
      { key: "estimated_tax", label: "Estimated Tax", type: "currency" },
      { key: "no_charge_amount", label: "No Charge Amount", type: "currency" },
      { key: "no_charge_amount_including_markup", label: "No Charge Amount (Including Markup)", type: "currency" },
      { key: "number", label: "Number" },
      { key: "pending_all_amount", label: "Pending All Amount", type: "currency" },
      { key: "pending_all_amount_including_markup", label: "Pending All Amount (Including Markup)", type: "currency" },
      { key: "pending_in_review_amount", label: "Pending In Review Amount", type: "currency" },
      { key: "pending_in_review_amount_including_markup", label: "Pending In Review Amount (Including Markup)", type: "currency" },
      { key: "pending_not_pricing_amount", label: "Pending Not Pricing Amount", type: "currency" },
      { key: "pending_not_pricing_amount_including_markup", label: "Pending Not Pricing Amount (Including Markup)", type: "currency" },
      { key: "pending_not_proceeding_amount", label: "Pending Not Proceeding Amount", type: "currency" },
      { key: "pending_not_proceeding_amount_including_markup", label: "Pending Not Proceeding Amount (Including Markup)", type: "currency" },
      { key: "pending_pricing_amount", label: "Pending Pricing Amount", type: "currency" },
      { key: "pending_pricing_amount_including_markup", label: "Pending Pricing Amount (Including Markup)", type: "currency" },
      { key: "pending_proceeding_amount", label: "Pending Proceeding Amount", type: "currency" },
      { key: "pending_proceeding_amount_including_markup", label: "Pending Proceeding Amount (Including Markup)", type: "currency" },
      { key: "pending_revised_amount", label: "Pending Revised Amount", type: "currency" },
      { key: "pending_revised_amount_including_markup", label: "Pending Revised Amount (Including Markup)", type: "currency" },
      { key: "quantity", label: "Quantity" },
      { key: "rejected_amount", label: "Rejected Amount", type: "currency" },
      { key: "rejected_amount_including_markup", label: "Rejected Amount (Including Markup)", type: "currency" },
      { key: "tax_code", label: "Tax Code" },
      { key: "tax_codes", label: "Tax Codes" },
      { key: "unit_cost", label: "Unit Cost", type: "currency" },
      { key: "unit_of_measure", label: "Unit of Measure" },
      { key: "void_amount", label: "Void Amount", type: "currency" },
      { key: "void_amount_including_markup", label: "Void Amount (Including Markup)", type: "currency" },
    ],
  },
  {
    slug: "commitment-change-order-markup",
    label: "Commitment Change Order Markup",
    fields: [
      { key: "label", label: "Markup" },
      { key: "type", label: "Type" },
      { key: "rate", label: "Rate" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "markup_name", label: "Markup Name" },
      { key: "markup_type", label: "Markup Type" },
      { key: "number", label: "Number" },
      { key: "percentage", label: "Percentage" },
    ],
  },
  {
    slug: "prime-contract-change-order-line-items",
    label: "Prime Contract Change Order Line Item",
    fields: [
      { key: "budget_code", label: "Budget Code" },
      { key: "description", label: "Description" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "approved_amount", label: "Approved Amount", type: "currency" },
      { key: "approved_changes_to_hours_budgeted", label: "Approved Changes To Hours Budgeted" },
      { key: "currency_code", label: "Currency Code" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "draft_amount", label: "Draft Amount", type: "currency" },
      { key: "estimated_tax", label: "Estimated Tax", type: "currency" },
      { key: "line_type", label: "Line Type" },
      { key: "no_charge_amount", label: "No Charge Amount", type: "currency" },
      { key: "number", label: "Number" },
      { key: "pending_all_amount", label: "Pending All Amount", type: "currency" },
      { key: "pending_in_review_amount", label: "Pending In Review Amount", type: "currency" },
      { key: "pending_not_pricing_amount", label: "Pending Not Pricing Amount", type: "currency" },
      { key: "pending_not_proceeding_amount", label: "Pending Not Proceeding Amount", type: "currency" },
      { key: "pending_pricing_amount", label: "Pending Pricing Amount", type: "currency" },
      { key: "pending_proceeding_amount", label: "Pending Proceeding Amount", type: "currency" },
      { key: "pending_revised_amount", label: "Pending Revised Amount", type: "currency" },
      { key: "quantity", label: "Quantity" },
      { key: "rejected_amount", label: "Rejected Amount", type: "currency" },
      { key: "tax_code", label: "Tax Code" },
      { key: "tax_codes", label: "Tax Codes" },
      { key: "unit_cost", label: "Unit Cost", type: "currency" },
      { key: "unit_of_measure", label: "Unit Of Measure" },
      { key: "void_amount", label: "Void Amount", type: "currency" },
    ],
  },
  {
    slug: "prime-contract-change-order-markup",
    label: "Prime Contract Change Order Markup",
    fields: [
      { key: "label", label: "Markup" },
      { key: "type", label: "Type" },
      { key: "amount", label: "Amount", type: "currency" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "markup_type", label: "Markup Type" },
      { key: "name", label: "Name" },
      { key: "percentage", label: "Percentage" },
      { key: "sequence_number", label: "Sequence Number" },
    ],
  },
  {
    slug: "prime-contract-line-items",
    label: "Prime Contract Line Item",
    fields: [
      { key: "amount", label: "Amount", type: "currency" },
      { key: "currency_code", label: "Currency Code" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "date_updated", label: "Date Updated", type: "date" },
      { key: "description", label: "Description" },
      { key: "estimated_tax", label: "Estimated Tax", type: "currency" },
      { key: "number", label: "Number" },
      { key: "quantity", label: "Quantity" },
      { key: "tax_code", label: "Tax Code" },
      { key: "tax_codes", label: "Tax Codes" },
      { key: "unit_cost", label: "Unit Cost", type: "currency" },
      { key: "unit_of_measure", label: "Unit Of Measure" },
    ],
  },
  {
    slug: "prime-contract-potential-change-orders",
    label: "Prime Contract Potential Change Order",
    fields: [
      { key: "amount", label: "Amount", type: "currency" },
      { key: "amount_including_markup", label: "Amount (Including Markup)", type: "currency" },
      { key: "approved_date", label: "Approved Date", type: "date" },
      { key: "assigned_to_current_workflow_step", label: "Assigned to Current Workflow Step" },
      { key: "change_reason", label: "Change Reason" },
      { key: "created_by", label: "Created By" },
      { key: "currency_code", label: "Currency Code" },
      { key: "current_workflow_response", label: "Current Workflow Response" },
      { key: "current_workflow_step", label: "Current Workflow Step" },
      { key: "current_workflow_step_due_date", label: "Current Workflow Step Due Date", type: "date" },
      { key: "date_created", label: "Date Created", type: "date" },
      { key: "description", label: "Description" },
      { key: "executed", label: "Executed" },
      { key: "field_change", label: "Field Change" },
      { key: "number", label: "Number" },
      { key: "paid_date", label: "Paid Date", type: "date" },
      { key: "paid_in_full", label: "Paid In Full" },
      { key: "private", label: "Private" },
      { key: "reference", label: "Reference" },
      { key: "request_received_from", label: "Request Received From" },
      { key: "revision", label: "Revision" },
      { key: "schedule_impact_days", label: "Schedule Impact (Days)" },
      { key: "signed_change_order_received_date", label: "Signed Change Order Received Date", type: "date" },
      { key: "status", label: "Status" },
      { key: "taxable_amount", label: "Taxable Amount", type: "currency" },
      { key: "title", label: "Title" },
      { key: "total_estimated_tax", label: "Total Estimated Tax", type: "currency" },
      { key: "workflow_assignment_duration_days", label: "Workflow Assignment Duration (Days)" },
    ],
  },
];

export const REPORT_RECORD_BY_SLUG: Record<string, ReportRecordEntity> =
  Object.fromEntries(REPORT_RECORD_ENTITIES.map((e) => [e.slug, e]));

export const REPORT_RECORD_SLUGS = REPORT_RECORD_ENTITIES.map((e) => e.slug);
