/**
 * Interactive text meetings for "SiteCommand Training" sandboxes.
 *
 * A scheduled task can carry a meeting: the Day panel hyperlinks the task text,
 * and clicking it opens /training/meeting?project=…&meeting=… in a new tab. The
 * meeting is a text conversation — the fake attendees (GC precon team personas)
 * talk in turn, and whenever it's the PM's (the trainee's) turn to weigh in, the
 * page prompts them to respond via text. The attendees' turns are generated by
 * Gemini (see app/api/projects/[id]/training/meetings/[meetingId]), grounded in
 * the agenda and facts defined here. The meeting sticks to the agenda; if the
 * trainee asks something off-script, the attendees answer the aside in character
 * and then steer back to the current agenda item.
 *
 * This module is pure, client-safe content (types + the meeting definitions +
 * lookup helpers) so both the Day panel and the API route can import it. Only
 * the Day-1 PM bid-review meeting is defined today; add future meetings to
 * TRAINING_MEETINGS.
 */

import type { SimRole } from "@/lib/simulation-constants";
import { TRAINING_SUBS } from "@/lib/training-emails";

export type MeetingSpeaker = {
  /** Stable key used in transcripts ("okafor"). "user" is reserved for the PM. */
  key: string;
  name: string;
  title: string;
  /** How this persona talks — grounding for the LLM, not shown in the UI. */
  style: string;
};

export type MeetingAgendaItem = {
  title: string;
  /** Grounding facts / talking points the attendees work from on this item. */
  points: string[];
};

export type MeetingTurn = {
  /** A speaker key from the meeting's speakers, or "user" for the PM. */
  speaker: string;
  text: string;
};

/**
 * A hidden "test" planted in the meeting. The attendees surface the clue
 * naturally (per `plant`) but never resolve it themselves — the checkpoint is
 * whether the PM catches it (flags it, asks about it, turns it into a
 * decision/action). Scored when the meeting adjourns; results land in the
 * saved minutes and the phase Job Review.
 */
export type MeetingCheckpoint = {
  id: string;
  /** Short label shown in the score card. */
  title: string;
  /** What catching it looks like — shown in the minutes and used for scoring. */
  expectation: string;
  /**
   * LLM-only instruction for how the attendees drop the clue in conversation
   * (never shown to the trainee, never dumped into fallback dialogue).
   */
  plant: string;
  /** Agenda item (0-based) where the clue belongs. */
  plantAgendaIndex: number;
  /**
   * Natural sentence appended to the canned fallback turn for that agenda item
   * so the clue still surfaces when Gemini is unavailable. Omit when the clue
   * is already carried by the agenda points / bid tab.
   */
  fallbackLine?: string;
  /**
   * Degraded scoring heuristic when Gemini is unavailable: the checkpoint
   * counts as caught if any PM turn contains any of these (case-insensitive).
   */
  keywords: string[];
};

export type TrainingMeeting = {
  id: string;
  role: SimRole;
  /** In-sim day the meeting's task lands on. */
  day: number;
  /** Exact TrainingTask.task string this meeting hyperlinks in the Day panel. */
  taskMatch: string;
  title: string;
  objective: string;
  deliverable: string;
  /** Attendees other than the PM. The first entry runs the meeting. */
  speakers: MeetingSpeaker[];
  agenda: MeetingAgendaItem[];
  /** Hidden tests scored against the transcript when the meeting adjourns. */
  checkpoints: MeetingCheckpoint[];
  /**
   * Deterministic opening turns (served without an LLM call) that run the
   * meeting up to the first point where the PM is expected to respond.
   */
  opening: MeetingTurn[];
};

// ---------------------------------------------------------------------------
// Day 1 — Bid review & vendor short-list (Project Manager)
// ---------------------------------------------------------------------------

/** Roster sub's seeded bid for a trade (keeps meeting numbers consistent with
 *  the buyout email threads). */
function rosterBid(trade: string): number {
  return TRAINING_SUBS.find((s) => s.trade === trade)?.bid ?? 0;
}

function money(value: number): string {
  return `$${Math.round(value).toLocaleString("en-US")}`;
}

/**
 * The bid tab the precon team walks through. One entry per trade: the estimate
 * line, each bidder (the seeded roster firm is flagged), and any flags the team
 * should raise. Competitor firms are fictional; the roster firm's number comes
 * from TRAINING_SUBS so the meeting agrees with the seeded buyout emails.
 */
type BidLine = { firm: string; amount: number | null; roster?: boolean; note?: string };
type BidTabTrade = { trade: string; estimate: number; bids: BidLine[]; flag?: string };

const BID_TAB: BidTabTrade[] = [
  {
    trade: "Concrete / Foundations",
    estimate: 4_400_000,
    bids: [
      { firm: "Bedrock Concrete", amount: rosterBid("Concrete / Foundations"), roster: true, note: "Clean scope, acknowledged Addenda 1–2" },
      { firm: "Apex Concrete Group", amount: 4_470_000 },
      { firm: "Southland Structures", amount: 4_690_000, note: "Excludes pump premiums" },
    ],
  },
  {
    trade: "Structural Steel / Framing",
    estimate: 6_600_000,
    bids: [
      { firm: "Palmetto Steel", amount: 6_540_000, note: "Did NOT acknowledge Addendum 2; excludes metal deck — likely a $400k+ scope gap" },
      { firm: "Ironclad Steel Erectors", amount: rosterBid("Structural Steel / Framing"), roster: true, note: "Full scope incl. deck; best erection schedule" },
      { firm: "TriState Erectors", amount: 7_150_000 },
    ],
    flag: "Apparent low (Palmetto) is not truly low once the deck gap and Addendum 2 are plugged.",
  },
  {
    trade: "Electrical",
    estimate: 5_500_000,
    bids: [
      { firm: "Voltura Electric", amount: rosterBid("Electrical"), roster: true, note: "Carries switchgear at ~42-week lead per distributor quote" },
      { firm: "Gridline Electrical", amount: 5_620_000 },
    ],
    flag: "Only two responsive bids — thin coverage; switchgear release is schedule-critical.",
  },
  {
    trade: "Plumbing",
    estimate: 3_250_000,
    bids: [
      { firm: "Cardinal Plumbing", amount: rosterBid("Plumbing"), roster: true },
      { firm: "BlueRiver Mechanical", amount: 3_180_000, note: "Close second — good leverage for the scope call" },
      { firm: "Pinnacle Plumbing", amount: 3_540_000 },
    ],
  },
  {
    trade: "HVAC / Mechanical",
    estimate: 5_000_000,
    bids: [
      { firm: "Northwind Mechanical", amount: rosterBid("HVAC / Mechanical"), roster: true, note: "Flagged long RTU lead times" },
      { firm: "Meridian Air Systems", amount: 5_060_000 },
      { firm: "Delta Comfort", amount: 5_390_000, note: "Excludes controls / BMS" },
    ],
  },
  {
    trade: "Fire Protection",
    estimate: 1_700_000,
    bids: [
      { firm: "Sentinel Fire Systems", amount: rosterBid("Fire Protection"), roster: true },
      { firm: "Guardian Sprinkler", amount: 1_720_000 },
    ],
  },
  {
    trade: "Roofing",
    estimate: 2_350_000,
    bids: [
      { firm: "Summit Ridge Roofing", amount: rosterBid("Roofing"), roster: true, note: "Manufacturer price-increase notice — number holds 45 days" },
      { firm: "Crestline Roofing", amount: 2_410_000 },
    ],
    flag: "Price hold expires in 45 days — award or lock pricing before then.",
  },
  {
    trade: "Glazing / Curtain Wall",
    estimate: 3_600_000,
    bids: [
      { firm: "MetroGlass", amount: 3_480_000, note: "Excludes engineering calcs and field mock-up; slow submittals on our last job with them" },
      { firm: "ClearSpan Glazing", amount: rosterBid("Glazing / Curtain Wall"), roster: true, note: "Full scope incl. engineering and mock-up" },
      { firm: "VistaPane", amount: 3_930_000 },
    ],
    flag: "Apparent low (MetroGlass) carries real scope gaps and performance risk.",
  },
];

/** Render the bid tab as plain text for the LLM's grounding context. */
export function bidTabText(): string {
  return BID_TAB.map((t) => {
    const lines = t.bids
      .map((b) => {
        const parts = [
          `  - ${b.firm}: ${b.amount === null ? "no bid" : money(b.amount)}`,
          b.roster ? "(the firm the team knows and has bid history with)" : "",
          b.note ? `— ${b.note}` : "",
        ].filter(Boolean);
        return parts.join(" ");
      })
      .join("\n");
    return `${t.trade} (estimate ${money(t.estimate)}):\n${lines}${t.flag ? `\n  FLAG: ${t.flag}` : ""}`;
  }).join("\n\n");
}

const BID_REVIEW_MEETING: TrainingMeeting = {
  id: "pm-day1-bid-review",
  role: "project_manager",
  day: 1,
  taskMatch:
    "Meet with preconstruction team to review bid results and develop short-list of vendors by trade",
  title: "Bid Review & Vendor Short-List",
  objective:
    "Walk the bid results trade by trade with the preconstruction team and agree on a short-list of vendors for each major trade.",
  deliverable: "Bid tab / vendor short-list",
  speakers: [
    {
      key: "okafor",
      name: "David Okafor",
      title: "Preconstruction Manager",
      style:
        "Runs the meeting. Organized and steady; keeps things moving through the agenda, summarizes decisions, and hands questions to the right person. Politely steers off-topic discussion back to the agenda.",
    },
    {
      key: "nguyen",
      name: "Rachel Nguyen",
      title: "Estimator",
      style:
        "Owns the numbers. Precise and quick with figures — quotes bid amounts, spreads vs. estimate, exclusions, and scope gaps from the bid tab. Flags anything that smells like a buyout bust.",
    },
    {
      key: "bennett",
      name: "Marcus Bennett",
      title: "Project Executive",
      style:
        "Big-picture and commercial. Cares about protecting budget and schedule, sub relationships, and risk. Speaks less often but weighs in on award strategy and pushes for decisions.",
    },
  ],
  agenda: [
    {
      title: "Bid coverage & overall results",
      points: [
        "All eight major trades received bids; coverage is decent overall.",
        "Two coverage concerns: Electrical drew only two responsive bids, and two trades have apparent-low bids with real scope gaps (Steel and Glazing).",
        "In aggregate the bids are close to estimate — roughly on budget if scope gaps are managed in the scope-review calls.",
      ],
    },
    {
      title: "Structural & envelope trades (concrete, steel, roofing, glazing)",
      points: [
        "Concrete: Bedrock is low with a clean scope — straightforward recommendation.",
        "Steel: Palmetto is apparent low but missed Addendum 2 and excludes metal deck (~$400k+ gap); Ironclad is full-scope with the best erection schedule.",
        "Roofing: Summit Ridge is low but their manufacturer price hold expires in 45 days — needs an early award or locked pricing.",
        "Glazing: MetroGlass is apparent low but excludes engineering and the field mock-up, and was slow on submittals last job; ClearSpan is full-scope.",
      ],
    },
    {
      title: "MEP trades (electrical, plumbing, HVAC, fire protection)",
      points: [
        "Electrical: Voltura is low with only two bids; their number carries switchgear at ~42-week lead — release timing is schedule-critical.",
        "Plumbing: Cardinal is low with BlueRiver a close second — good leverage going into scope calls.",
        "HVAC: Northwind is low and flagged long RTU lead times; Delta Comfort excludes controls/BMS.",
        "Fire protection: Sentinel is low with a clean number.",
      ],
    },
    {
      title: "Short-list decisions by trade",
      points: [
        "Go trade by trade and have the PM confirm the short-list (typically the top one or two firms per trade to take into scope-review calls).",
        "Team recommendation: Bedrock (concrete), Ironclad over Palmetto (steel — gap risk), Voltura (electrical), Cardinal + BlueRiver (plumbing), Northwind (HVAC), Sentinel (fire), Summit Ridge (roofing — mind the price hold), ClearSpan over MetroGlass (glazing — scope/performance risk).",
        "The PM owns the final call; the team pushes back respectfully if a pick carries risk they've flagged.",
      ],
    },
    {
      title: "Action items & award targets",
      points: [
        "PM to schedule scope-review calls with short-listed firms for the major trades next week.",
        "Prioritize long-lead: switchgear (electrical) and RTUs (HVAC) need early release / LOIs to protect the schedule.",
        "Roofing pricing must be locked before the 45-day hold expires.",
        "Target: awards out by end of next week; the documented bid tab / short-list is the deliverable from this meeting.",
      ],
    },
  ],
  checkpoints: [
    {
      id: "slab-milestone",
      title: "30-day slab-pour milestone",
      expectation:
        "Catches the owner-agreement milestone (first slab-on-grade poured within 30 days of contract start) and connects it to expediting the concrete award — awarding Bedrock immediately and getting mobilization moving.",
      plant:
        "While the concrete trade is being discussed, have Marcus Bennett mention IN PASSING that the owner agreement carries a milestone with liquidated damages: the first slab-on-grade must be poured within 30 days of contract start (NTP). Drop it as a side remark and move on — do NOT spell out what it means for buyout sequencing and do NOT propose the fix yourselves. If the PM never picks it up, let it go unresolved.",
      plantAgendaIndex: 1,
      fallbackLine:
        "Marcus also flagged something buried in the owner agreement — a milestone with liquidated damages requiring the first slab pour within 30 days of contract start.",
      keywords: ["slab", "30 day", "30-day", "thirty day", "liquidated", "milestone"],
    },
    {
      id: "steel-scope-gap",
      title: "Steel apparent-low scope gap",
      expectation:
        "Doesn't take Palmetto's apparent-low steel bid at face value — picks Ironclad, or requires the metal-deck / Addendum 2 gap plugged before any award to Palmetto.",
      plant:
        "The bid tab already carries this: Palmetto Steel is apparent low but missed Addendum 2 and excludes metal deck. Present the numbers factually and let the PM make the call — don't make the decision for them.",
      plantAgendaIndex: 1,
      keywords: ["ironclad", "palmetto", "deck", "addendum"],
    },
    {
      id: "roofing-price-hold",
      title: "Roofing 45-day price hold",
      expectation:
        "Acts on the roofing price hold — commits to awarding Summit Ridge or locking their pricing before the 45-day manufacturer hold expires.",
      plant:
        "The bid tab already carries the 45-day manufacturer price hold on Summit Ridge's number. State it as a fact; let the PM decide the urgency.",
      plantAgendaIndex: 1,
      keywords: ["price hold", "45-day", "45 day", "lock roofing", "lock pricing", "lock the roofing"],
    },
    {
      id: "switchgear-lead",
      title: "Switchgear long-lead release",
      expectation:
        "Flags the ~42-week switchgear lead time and calls for an early electrical award, LOI, or early switchgear release to protect the schedule.",
      plant:
        "The bid tab already carries Voltura's ~42-week switchgear lead. Mention it with the electrical numbers; don't propose the early release yourselves.",
      plantAgendaIndex: 2,
      keywords: ["switchgear", "loi", "early release", "long lead", "long-lead"],
    },
    {
      id: "glazing-risk",
      title: "Glazing apparent-low risk",
      expectation:
        "Avoids MetroGlass's scope-gapped low bid — short-lists ClearSpan, or requires engineering and the field mock-up included before considering MetroGlass.",
      plant:
        "The bid tab already carries MetroGlass's exclusions (engineering calcs, field mock-up) and their submittal history. Present it factually and let the PM decide.",
      plantAgendaIndex: 1,
      keywords: ["clearspan", "metroglass", "mock-up", "mockup"],
    },
  ],
  opening: [
    {
      speaker: "okafor",
      text: "Thanks for making time on day one — this is the most important hour of your week. Purpose of this meeting is simple: walk the bid results trade by trade and leave with a short-list of vendors for each major trade so you can start scope calls. Agenda is: coverage and overall results, structural and envelope trades, MEP trades, short-list decisions, then action items and award targets. Rachel, want to start us off with coverage?",
    },
    {
      speaker: "nguyen",
      text: "Sure. We got bids on all eight major trades, so coverage is decent overall. Two things to keep in mind as we go: Electrical only drew two responsive bids, and on Steel and Glazing the apparent low bidders both have real scope gaps — so \"low\" isn't low once you plug the holes. In aggregate we're sitting right around the estimate, which is a good place to start buyout from.",
    },
    {
      speaker: "bennett",
      text: "And from my side — the goal today is to protect the budget and the schedule. A cheap number with a scope gap is how buyout busts happen, so let's short-list firms we can actually build with.",
    },
    {
      speaker: "okafor",
      text: "Agreed. Before we dig into the trades — any questions on how the bids came in, or any trade you want us to spend extra time on?",
    },
  ],
};

/** All defined meetings. Add future meetings here. */
export const TRAINING_MEETINGS: TrainingMeeting[] = [BID_REVIEW_MEETING];

export function getTrainingMeeting(id: string): TrainingMeeting | null {
  return TRAINING_MEETINGS.find((m) => m.id === id) ?? null;
}

/** The meeting hyperlinked by a scheduled task, if any. */
export function meetingForTask(role: SimRole, day: number, task: string): TrainingMeeting | null {
  return (
    TRAINING_MEETINGS.find((m) => m.role === role && m.day === day && m.taskMatch === task) ?? null
  );
}

/** Display lookup for a transcript speaker key. */
export function meetingSpeaker(meeting: TrainingMeeting, key: string): MeetingSpeaker | null {
  return meeting.speakers.find((s) => s.key === key) ?? null;
}
