ALTER TABLE projects
  ADD COLUMN IF NOT EXISTS erp_sync BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS erp_job_cost_sync BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS prevent_overbilling BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS non_commitment_costs BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS test_project BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS sage_300_id TEXT;
